### ISSUE TITLE
Bug: signature method not working

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#127]
Petr is calling 'signature' method from new frontend:

[![Screen Shot 2016-10-04 at 23.58.27.png](https://s21.postimg.org/a8wxf5kon/Screen_Shot_2016_10_04_at_23_58_27.png)](https://postimg.org/image/ly0x34bn7/)

1) POST https://dynamisapp-develop.herokuapp.com/api/v1/policies/
2) PUT https://dynamisapp-develop.herokuapp.com/api/v1/policies/31/

3) **POST https://dynamisapp-develop.herokuapp.com/api/v1/policies/31/signature**

[![Screen Shot 2016-10-04 at 15.02.02.png](https://s15.postimg.org/9j78u6g8r/Screen_Shot_2016_10_04_at_15_02_02.png)](https://postimg.org/image/p4oke4s6v/)

You can try it yourself on the new frontend: 
https://dynamis-frontend-develop.herokuapp.com

API documentation is here: http://docs.dynamis1.apiary.io/#reference/0/policies/sign-a-policy

**Comment by chepe4pi** [comment]
bug in frontend probably
