### ISSUE TITLE
Refactor accounts API

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#13]
1) Исследовать - как максимально просто и качественно переделать пути в /api/v1/accounts/{id}/settings и /api/v1/accounts/{id}/policies/{policy_id}/something

2) Написать код для **accounts** и показать мне (чтобы я оценил - насколько это нам нужно):
/api/v1/accounts/settings/{id} ->/api/v1/accounts/{id}/settings
/api/v1/accounts/keybase/{id} ->/api/v1/accounts/{id}/keybase

**Comment by chepe4pi** [comment]
1) https://github.com/alanjds/drf-nested-routers - возможно при помощи пакета
2) сделаю pull request

**Comment by AnthonyAkentiev** [comment]
ok
