### ISSUE TITLE
Sign method - check JSON please

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#147]
Петр сейчас вызывает метод для подписи. Это 89 у него таск - https://waffle.io/dynamisdao/frontend2/cards/57f3a8822545a9f800bbed0b

Там нужно сформировать правильный JSON.
http://docs.dynamis1.apiary.io/#reference/0/policies/sign-a-policy . 

У него что-то не получается. Посмотри плиз его:
1) дай ему валидный вариант JSON'а
2) посмотри в доке - все ли там верно? возможно, какие-то поля разъехались у нас между кодом/документацией.

**Comment by chepe4pi** [comment]
если 400 ошибка (ошибка валидации) то бекенд всегда возвращает описание того что он счел невалидным. его можно посмотреть в chrome кликнув по ссылке запроса на который вернул ответ с 400 кодом.
в данном случае - пустой keybase

[![Screen Shot 1](https://s18.postimg.org/rfu7qpt39/Screenshot_from_2016_10_12_12_49_00.png)](https://postimg.org/image/rfu7qpt39/)

[![Screen Shot 2](https://s18.postimg.org/91jomqgsl/Screenshot_from_2016_10_12_12_49_25.png)](https://postimg.org/image/91jomqgsl/)

**Comment by pitronalldak** [comment]
Почему просто нельзя где-нибудь опубликовать пример валидного JSON,  выглядит все так, как будто я дурак)) хотя я должен сидеть и угадывать формат JSON по ошибкам в recponse

**Comment by AnthonyAkentiev** [comment]
@chepe4pi Алексей, займись плиз. Петру нужно помочь. Не хочу быть испорченным телефоном.

**Comment by chepe4pi** [comment]
[![Screenshot from 2016-10-13 00-28-18_2.png](https://s14.postimg.org/ue690qzup/Screenshot_from_2016_10_13_00_28_18_2.png)](https://postimg.org/image/nnprrbcot/)

[![Screenshot from 2016-10-13 00-28-58.png](https://s15.postimg.org/5mmkcf9qj/Screenshot_from_2016_10_13_00_28_58.png)](https://postimg.org/image/6c5cosa9z/)

вот два json который отправляется на подпись со страрого фронтенда и нового
отличие в том что у старого нет верхнего уровня {'data' : ... }
второе отличие что в новом фронтенде в "identity" - "verification_data" - нет поля "username"
также в новом появились поля questions, но это не должно влиять
