### ISSUE TITLE
Test Smart Deposit in new frontend

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#226]
Мы с Петей тестировали вчера несколько раз.
Всё переходит в состояние waiting нормально.

Заметили следующее:
1) Кол-во ETH меняется уже после того, как состояние перешло в **waiting**. Такого не должно быть, тк мы же фиксируем кол-во денег на 1 час. Даже если курс скачет очень сильно.

2) Smart Deposit так и не переключается в 'received'.
Мы ждали по 30-40 минут. 

Пожалуйста протестируй все сам. 
Можешь зайти на новый фронтенд http://dynamis-frontend-develop.herokuapp.com/

ТОЛЬКО через http )))

Возможно из-за как раз скачков цены?

**Comment by chepe4pi** [comment]
Баг со скачками цены поправил

**Comment by chepe4pi** [comment]
Трансакция не находиться по тому что в запросе - https://dynamisapp-develop.herokuapp.com/api/v1/policies/{id}/smart_deposit/send - в поле "from_address" нужно указывать адрес с которого бекенд должен ожидать трансакию, а не системмный адрес, на который мы отправляем трансакцию.

**Comment by chepe4pi** [comment]
Желательно делать этот запрос до реального отправления трансакции

**Comment by AnthonyAkentiev** [comment]
Ок. Спасибо
