### ISSUE TITLE
Bug: click on 'Submit Application' -> ERROR

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#38]
POST /api/v1/policies/1/submit/ HTTP/1.1" 404

[![bug.png](https://s15.postimg.org/y91mzb1e3/bug.png)](https://postimg.org/image/cze0ogl3b/)

1) Log in
2) "My policy"
3) "Start one"
4) Fill all fields until "Submit Application" button is shown
5) Click on "Submit Application"

**Comment by chepe4pi** [comment]
/api/v1/policies/1/submit/ - wrong url
http://docs.dynamis1.apiary.io/#reference/0/policies/sign-a-policy
