### ISSUE TITLE
bug: "accounts_user"."is_keybase_verified"

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#52]
https://dynamisapp.herokuapp.com/

---

ProgrammingError at /accounts/my-policy/
column accounts_user.linkedin_account does not exist
LINE 1: ...username", "accounts_user"."is_keybase_verified", "accounts_...
                                                             ^
Request Method: GET
Request URL:    http://dynamisapp.herokuapp.com/accounts/my-policy/
Django Version: 1.9.4
Exception Type: ProgrammingError
Exception Value:  
column accounts_user.linkedin_account does not exist
LINE 1: ...username", "accounts_user"."is_keybase_verified", "accounts_...
                                                             ^
Exception Location: /app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:  /app/.heroku/python/bin/python
Python Version: 2.7.12
Python Path:  
['/app',
 '/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-25.2.0-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg']
Server time:    Thu, 8 Sep 2016 12:13:47 +0000

**Comment by chepe4pi** [comment]
из-за миграций
