### ISSUE TITLE
Bug: column policy_policyapplication.rejected_count does not exist

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#61]
column policy_policyapplication.rejected_count does not exist
LINE 1: ..."."is_signed", "policy_policyapplication"."data", "policy_po...

Request Method: GET
Request URL:    http://dynamisapp-develop.herokuapp.com/admin/accounts/policies/
Django Version: 1.9.4
Exception Type: ProgrammingError
Exception Value:  
column policy_policyapplication.rejected_count does not exist
LINE 1: ..."."is_signed", "policy_policyapplication"."data", "policy_po...
                                                             ^
Exception Location: /app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:  /app/.heroku/python/bin/python
Python Version: 2.7.12
Python Path:  
['/app',
 '/app/.heroku/python/bin',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-25.2.0-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg']
Server time:    Tue, 20 Sep 2016 13:08:48 +0000

[![Screen Shot 2016-09-20 at 16.10.50.png](http://s14.postimg.org/tttdhkv9d/Screen_Shot_2016_09_20_at_16_10_50.png)](http://postimg.org/image/hrxznfm0t/)

**Comment by chepe4pi** [comment]
я еще вчера все пофиксл, но есть какая-то проблема в сценарии деплоя. видимо не отрабатывает команда migrate, и чтобы все заработало приходиться ее рукам запускать после деплоя. сейчас посмотрю в чем проблема
