### ISSUE TITLE
Risk Assessment - populate all controls

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/dynamisapp#67]
> By Joshua:  "You need to evaluate the following information to make good bets:
> 1. How complete is the identity information?
> 2. How much information does the employment history give you?
> 3. What did they put down as a smart deposit?"

User ID: TODO
User Name: TODO
LinkedIn: TODO
...
etc

[![Screen Shot 2016-09-22 at 13.58.40.png](http://s21.postimg.org/a0va3mznb/Screen_Shot_2016_09_22_at_13_58_40.png)](http://postimg.org/image/6u0qk0f77/)

**Comment by chepe4pi** [comment]
remove unused social media
